spring.application.name=sistema-gestion

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:motorepuestos_tato}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

miapi.token=${API_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNjEsImV4cCI6MTc2MDM4Mzc4N30.K6fcsDrgk9mHqXVFDaiJK5fRt7ayS87TNxkdDmdCJpo}
miapi.url.base=https://miapi.cloud/v1/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tato.975523@gmail.com
spring.mail.password=${MAIL_PASSWORD:zzozrppekwkxxhzp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true